### ISSUE TITLE
Rename Bilaan to Bilaan (Koronadal)

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#112]
The name of [Bilaan](http://wals.info/languoid/lect/wals_code_biq) should be changed to Bilaan (Koronadal) and linked to ISO code [bpr].

**Comment by xflr6** [comment]
Just for confirmation: drop the link to ISO codes [bps] and [smk], right?

https://github.com/clld/wals3/blob/44a12ddce7d6dd000c4bbfc24ca111d20ce48fe7/migrations/pending/update_biq_mxx_dan_pkm_acr_guq_rsh_krd_khv_wuc_%20keo_mug_kiw_amu_prc_don.py#L23-L25

**Comment by xrotwang** [comment]
yes
