### ISSUE TITLE
Mirativity

### ISSUE THREAD

**Issue by ADormant** [clld/wals-data#120]
Hello, you seem to be missing mirativity which is a separate grammatical category from evidentiality.
http://wals.info/feature
http://alexandria.ucsb.edu/downloads/8g84mm42z

**Comment by xrotwang** [comment]
Unfortunately we do not have any concrete plans of adding more chapters/features to WALS. So unless the editors - Matthew Dryer and Martin Haspelmath - agree to add more chapters, mirativity will not find it's way into WALS.
