### ISSUE TITLE
Writing Systems needs more data points

### ISSUE THREAD

**Issue by OneNationUnderCanadia** [clld/wals-data#121]
http://wals.info/feature/141A#3/50.29/196.70 It currently has only 6 data points (Vai, Cherokee, Cree (Plains), Ojibwa (Eastern), Chipewyan, and Inuktitut (Quebec-Labrador)).  One might start by adding English, Spanish, French, Greek (Modern), Russian, etc (all Alphabetic), Arabic (Egyptian) and Hebrew (Modern) (both Consonantal) Hindi (Alphasyllabic) Mandarin (Logographic) and Japanese (Mixed logographic–syllabic) so that all of the types mentioned are at least represented on the map, but preferably it would have a better sample, at least 100.

**Comment by xrotwang** [comment]
Most of the WALS chapters are not updated by the respective authors anymore, and we don't have (or plan to have) a procedure for passing on authorship. So, unfortunately, there is no easy way of adding data to WALS - on the other hand it should be simple enough to enrich the data in your personal fork of this repository.
