### ISSUE TITLE
Diola-Kasa (csk) not linked to a country where it is spoken

### ISSUE THREAD

**Issue by xflr6** [clld/wals-data#135]
```python
In [1]: import pandas as pd
   ...: query = '''SELECT l.id, l.name
   ...: FROM LANGUAGE AS l
   ...: WHERE NOT EXISTS (
   ...:   SELECT 1 FROM countrylanguage AS cl WHERE cl.language_pk = l.pk)
   ...: ORDER BY l.id'''
   ...: pd.read_sql_query(query, 'postgresql://postgres@/wals', index_col='id')
Out[1]: 
                   name
id                     
csk          Diola-Kasa
isl  International Sign
```
Should [WALS csk](http://wals.info/languoid/lect/wals_code_csk) maybe link to [GM](http://wals.info/country/GM), [GW](http://wals.info/country/GW), and [SN](http://wals.info/country/SN) following Glottolog [jola1262](http://glottolog.org/resource/languoid/id/jola1262)?

**Comment by xrotwang** [comment]
The links between countries and languages haven't been updated in a long time. Probably most people use this information from Glottolog anyway, so I'd rather de-emphasize that WALS has this data as well.

**Comment by xflr6** [comment]
Thanks. Close this then? #99 as well?
