### ISSUE TITLE
Missing language: Friulian

### ISSUE THREAD

**Issue by liuq** [clld/wals-data#137]
I noticed that in the list of languages Friulian (ISO 693-2 Fur, https://en.wikipedia.org/wiki/Friulian_language, Paola Benincà & Laura Vanelli. “Friulian”, in The Oxford Guide to the Romance Languages, eds. Adam Ledgeway & Martin Maiden. Oxford: Oxford University Press, 2016, pp. 139–153) is missing. Although it's a Rhaeto-Romance language close to the Ladin it has its own peculiarities and it's one of the four official languages of the Italian region Friuli–Venezia Giulia. Moreover it has a long literary tradition, dating back to the 14th century.

I think it should deserve to be listed.

**Comment by xrotwang** [comment]
The list of languages covered in WALS is not meant to be an exhaustive list of all languages of the world; but it's rather the union of all languages that authors of any of the WALS chapters had data on and wanted to include in the analysis.
