### ISSUE TITLE
Rename Dong

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#71]
The language [Dong](http://wals.info/languoid/lect/wals_code_don) should be renamed Dong (Southern) and linked only to ISO code kmc.

**Comment by xflr6** [comment]
Also link it to [sout2741](http://glottolog.org/resource/languoid/id/sout2741)?
https://github.com/clld/wals3/blob/76aeee612b0d52636ee0f15dc839b015c39f75f5/migrations/pending/update_biq_mxx_dan_pkm_acr_guq_rsh_krd_khv_wuc_%20keo_mug_kiw_amu_prc_don.py#L76-L80
