### ISSUE TITLE
Update ISO code for Dan

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#97]
The ISO of [Dan](http://wals.info/languoid/lect/wals_code_dan) code needs to be changed to [dnj].

**Comment by xflr6** [comment]
Also [daf] -> [dnj] (retirement/split) for Glottolog [dann1241](http://glottolog.org/resource/languoid/id/dann1241) @d97hah?
https://github.com/clld/glottolog/blob/c28ca49bafc5035398579fdc09442c228199f7c0/languoids/tree/mand1469/east2697/sout3140/guro1245/guro1246/dant1235/dann1241/md.ini#L3-L6

**Comment by d97hah** [comment]
No, I don't think the split is justified (in the sense of intelligibility)
by the request.

2017-10-24 12:33 GMT+02:00 Sebastian Bank <notifications@github.com>:
