### ISSUE TITLE
Change country association from Sudan to South Sudan

### ISSUE THREAD

**Issue by xrotwang** [clld/wals-data#99]
The identification of countries in WALS languages which WALS lists as spoken in Sudan need to be changed to South Sudan.

In principle, there might be languages spoken in both Sudan and South Sudan, but as far as I can determine, there are no such languages (at least among the languages in WALS).

This includes the following (in some cases, WALS lists more than one country and for these, the other countries should remain the same):
- Acholi
- Shilluk
- Dinka
- Luwo
- Nuer
- Anywa
- Kukú
- Päri
- Bari
- Murle
- Baale
- Tennet
- Didinga
- Chai
- Kresh
- Yulu
- Binga
- Aja
- Bongo
- Jur Mödö
- Moru
- Avokaya
- Komo
- Ndogo
- Mündü
- Zande
- Baka (in Sudan)

**Comment by xrotwang** [comment]
Hm. There's no other new countries recently, right?

**Comment by xflr6** [comment]
Some in 2010:
```python
In [1]: import pandas as pd
   ...: url = 'https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2'
   ...: df, = pd.read_html(url, match='Andorra', header=0, index_col='Code')
   ...: df.sort_values(by=['Year'], ascending=False).iloc[:12, :-1]
Out[1]: 
                          Country name  Year ccTLD     ISO 3166-2
Code                                                             
SS                         South Sudan  2011   .ss  ISO 3166-2:SS
CW                             Curaçao  2010   .cw  ISO 3166-2:CW
BQ    Bonaire, Sint Eustatius and Saba  2010   .bq  ISO 3166-2:BQ
SX           Sint Maarten (Dutch part)  2010   .sx  ISO 3166-2:SX
BL                    Saint Barthélemy  2007   .bl  ISO 3166-2:BL
MF          Saint Martin (French part)  2007   .mf  ISO 3166-2:MF
GG                            Guernsey  2006   .gg  ISO 3166-2:GG
IM                         Isle of Man  2006   .im  ISO 3166-2:IM
JE                              Jersey  2006   .je  ISO 3166-2:JE
ME                          Montenegro  2006   .me  ISO 3166-2:ME
RS                              Serbia  2006   .rs  ISO 3166-2:RS
AX        Aland Islands !Åland Islands  2004   .ax  ISO 3166-2:AX
```

**Comment by xrotwang** [comment]
Ok. I think updating the Sudan links would make sense - it seems to be singular enough.

**Comment by xflr6** [comment]
Going through the list. Currently not linked to [SD](http://wals.info/country/SD) (only to [Ethiopia](http://wals.info/country/ET), add it?):
- [Anywa](http://wals.info/languoid/lect/wals_code_any)
- [Chai](http://wals.info/languoid/lect/wals_code_cai)

Baka (in Sudan) was renamed to [Baka (in South Sudan)](http://wals.info/languoid/lect/wals_code_bka)

Assuming [the list](https://github.com/clld/wals-data/issues/99#issue-161364878) is exhaustive (?), the following languages keep [SD](http://wals.info/country/SD) (intended?):

- [Arabic (Modern Standard)](http://wals.info/languoid/lect/wals_code_ams)
- [Beja](http://wals.info/languoid/lect/wals_code_bej)
- [Beria](http://wals.info/languoid/lect/wals_code_zag)
- [Berta](http://wals.info/languoid/lect/wals_code_ber)
- [Daju (Dar Fur)](http://wals.info/languoid/lect/wals_code_ddf)
- [Fur](http://wals.info/languoid/lect/wals_code_fur)
- [Ghulfan](http://wals.info/languoid/lect/wals_code_nbh)
- [Gumuz](http://wals.info/languoid/lect/wals_code_gmz)
- [Ingessana](http://wals.info/languoid/lect/wals_code_igs)
- [Jomang](http://wals.info/languoid/lect/wals_code_jom)
- [Kadugli](http://wals.info/languoid/lect/wals_code_kad)
- [Kanuri](http://wals.info/languoid/lect/wals_code_knr)
- [Katcha](http://wals.info/languoid/lect/wals_code_ktc)
- [Katla](http://wals.info/languoid/lect/wals_code_ktl)
- [Krongo](http://wals.info/languoid/lect/wals_code_kro)
- [Lafofa](http://wals.info/languoid/lect/wals_code_laf)
- [Ma'di](http://wals.info/languoid/lect/wals_code_mad)
- [Masakin](http://wals.info/languoid/lect/wals_code_msk)
- [Masalit](http://wals.info/languoid/lect/wals_code_msl)
- [Midob](http://wals.info/languoid/lect/wals_code_mid)
- [Miisiirii](http://wals.info/languoid/lect/wals_code_mii)
- [Moro](http://wals.info/languoid/lect/wals_code_mro)
- [Nobiin](http://wals.info/languoid/lect/wals_code_nob)
- [Nubian (Dongolese)](http://wals.info/languoid/lect/wals_code_nbd)
- [Nyimang](http://wals.info/languoid/lect/wals_code_nyi)
- [Orig](http://wals.info/languoid/lect/wals_code_ori)
- [Otoro](http://wals.info/languoid/lect/wals_code_otr)
- [Rashad](http://wals.info/languoid/lect/wals_code_ras)
- [Shatt](http://wals.info/languoid/lect/wals_code_sht)
- [Tama](http://wals.info/languoid/lect/wals_code_tma)
- [Temein](http://wals.info/languoid/lect/wals_code_tmn)
- [Tima](http://wals.info/languoid/lect/wals_code_tia)
